package com.example.demo.greeting.service;

import com.example.demo.common.repository.FunctionalIdGenerator;
import com.example.demo.greeting.model.Greeting;
import com.example.demo.greeting.repository.GreetingRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import java.time.Clock;
import java.time.Instant;
import java.util.Optional;

@Service
public class GreetingService {

    private final FunctionalIdGenerator idGenerator;
    private final GreetingRepository repository;
    private final Clock clock;

    public GreetingService(FunctionalIdGenerator idGenerator, GreetingRepository repository, Clock clock) {
        this.idGenerator = idGenerator;
        this.repository = repository;
        this.clock = clock;
    }

    public Greeting createGreeting(String message, String recipient) {
        Instant now = Instant.now(clock);
        
        // Create entity - TSID (id) is auto-generated by Hibernate via @Tsid annotation
        Greeting entity = new Greeting(recipient, message, now);

        // Generate human-readable functional ID (e.g., GRE-2025-000042)
        // This runs in its own transaction to ensure sequence integrity
        String reference = idGenerator.generate("greeting_sequence", "GRE");
        entity.setReference(reference);

        // Save: Both TSID and functional ID are now set
        return repository.save(entity);
    }

    public Page<Greeting> getGreetings(int page, int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by(Sort.Direction.DESC, "createdAt"));
        return repository.findAll(pageable);
    }

    public Optional<Greeting> getGreeting(Long id) {
        return repository.findById(id);
    }

    public Optional<Greeting> updateGreeting(Long id, String message, String recipient) {
        return repository.findById(id)
                .map(existing -> {
                    existing.setMessage(message);
                    existing.setRecipient(recipient);
                    return repository.save(existing);
                });
    }

    public Optional<Greeting> patchGreeting(Long id, String message, String recipient) {
        return repository.findById(id)
                .map(existing -> {
                    if (message != null) {
                        existing.setMessage(message);
                    }
                    if (recipient != null) {
                        existing.setRecipient(recipient);
                    }
                    return repository.save(existing);
                });
    }

    public boolean deleteGreeting(Long id) {
        if (repository.existsById(id)) {
            repository.deleteById(id);
            return true;
        }
        return false;
    }
}
