/**
 * API module - OpenAPI generated controller interfaces and DTOs.
 *
 * <p>This module is marked as OPEN because it contains generated code from
 * OpenAPI specifications that is used across multiple domain modules.</p>
 *
 * <p>Note: This package and its subpackages (v1/controller, v1/model) are
 * auto-generated by openapi-generator-maven-plugin.</p>
 */
@org.springframework.modulith.ApplicationModule(
        type = org.springframework.modulith.ApplicationModule.Type.OPEN
)
package com.example.demo.api;
