package com.example.demo.greeting.model;

import com.example.demo.common.domain.AbstractBaseEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;

/**
 * Greeting entity with dual identity strategy:
 * - id (Long): TSID auto-generated by Hibernate for performance and sortability
 * - reference (String): Human-readable functional ID (e.g., GRE-2025-000042)
 */
@Entity
@Table(name = "greeting")
public class Greeting extends AbstractBaseEntity {

    @Getter
    @Setter
    @Column(name = "reference", nullable = false, unique = true, length = 32)
    private String reference;

    @Getter
    @Setter
    @Column(name = "recipient", nullable = false)
    private String recipient;

    @Getter
    @Setter
    @Column(name = "message", nullable = false)
    private String message;

    @Getter
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    protected Greeting() {  }

    public Greeting(String recipient, String message, Instant createdAt) {
        this.recipient = recipient;
        this.message = message;
        this.createdAt = createdAt;
    }

}
