package com.example.demo.greeting.model;

import com.example.demo.common.domain.AbstractBaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.envers.Audited;

/**
 * Greeting entity with dual identity strategy:
 * - id (Long): TSID auto-generated by Hibernate for performance and sortability
 * - reference (String): Human-readable functional ID (e.g., GRE-2025-000042)
 */
@Entity
@Table(name = "greeting")
@Audited
public class Greeting extends AbstractBaseEntity {

    @Getter
    @Setter
    @Column(name = "reference", nullable = false, unique = true, length = 32, updatable = false)
    private String reference;

    @Getter
    @Setter
    @Column(name = "recipient", nullable = false)
    private String recipient;

    @Getter
    @Setter
    @Column(name = "message", nullable = false)
    private String message;


    public Greeting() {  }

    public Greeting(String recipient, String message) {
        this.recipient = recipient;
        this.message = message;
    }

}
