import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Product',
      link: {
        type: 'doc',
        id: 'product/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'product',
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'doc',
        id: 'architecture/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {
        type: 'doc',
        id: 'operations/intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'operations',
        },
      ],
    },
    {
        type: 'category',
        label: 'Developer Guides',
        link: {
          type: 'doc',
          id: 'developer-guides/intro',
        },
        items: [
          {
            type: 'autogenerated',
            dirName: 'developer-guides',
          },
        ],
      },
    {
        type: 'category',
        label: 'Misc',
        items: [
            'architecture',
            'backlogs',
            'readme-archive',
            'todos',
        ]
    }
  ],
};

export default sidebars;
